[package]
name = "ts7200"
version = "0.1.0"
authors = ["Daniel Prilik <danielprilik@gmail.com>"]
edition = "2018"

[dependencies]
arm7tdmi-rs = { path = "../arm7tdmi-rs", features = ["advanced_disasm"] }
gdbstub = { path = "../gdbstub", features = ["std"] }

byteorder = "1.3"
goblin = "0.1"
log = "0.4"
pretty_env_logger = "0.3"
termion = "1.5.4"
